import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import "simplebar-react/dist/simplebar.min.css";

import { cn } from "@/lib/utils";

import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QnA Doc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en" className="light">
        <body
          className={cn(
            "min-h-screen font-sans antialiased grainy",
            font.className
          )}>
          <Toaster />
          <Navbar />
          {children}
        </body>
      </html>
    </Providers>
  );
}
